config/routes.rb
PetBnB::Application.routes.draw do
  root 'static_pages#index'

  resource :session, only: [:create, :destroy]
  resources :users, defaults: { format: :json }, only: [:create, :show]

  namespace :api, defaults: { format: :json } do
    resources :listings, only: [:show]
    resources :images, only: [:create, :show]
    resources :reservations, only: [:create, :show]
    get '/search' => 'listings#search'
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :listing

  validates :url, :listing_id, presence: true
  validates :url, uniqueness: true
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_many :images, -> { order "url ASC" }
  has_many :reservations, -> { order "start_date ASC" }

  validates :name, :description, :latitude, :longitude, :address,
            :price_daily, :user_id, presence: true

  def has_overlaps?(other_res)
    reservations.any? do |res|
      res.overlaps?(other_res)
    end
  end

  def self.save_to_db(params)
    debugger
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :booker, class_name: :User, foreign_key: :booker_id
  belongs_to :listing

  validates :booker_id, :listing_id, :start_date, :end_date,
            presence: true

  def try_booking
    listing = Listing.find(listing_id)
    if listing.booked && listing.has_overlaps?(self)
      errors[:listing] = 'is already booked on those dates'
      return false
    else
      self.save!
      listing.update(booked: true)
    end

    return true
  end

  def overlaps?(other_res)
    start_date < other_res.end_date && other_res.start_date < end_date
  end
end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :user

  validates :session_token, :user_id, presence: true
  validates :session_token, uniqueness: true

  before_validation :ensure_session_token

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def remove_session!
    Session.destroy(id)
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sessions
  has_many :listings, -> { order "name ASC" }
  has_many :reservations, -> { order "start_date ASC" },
                          foreign_key: :booker_id

  validates :email, :password_digest, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  def self.find_by_credentials(params)
    user = User.find_by_email(params[:email])
    return nil if user.nil?
    user.is_password?(params[:password]) ? user : nil
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end
end

app/controllers/api/images_controller.rb
module Api
  class ImagesController < ApplicationController
    def create
      @image = Image.new(image_params)
      if @image.save
        render json: @image
      else
        render json: @image.errors.full_messages,
                     status: :unprocessable_entity
      end
    end

    def show
      @image = Image.find(params[:id])
      render json: @image
    end
  end
end

app/controllers/api/listings_controller.rb
module Api
  class ListingsController < ApplicationController
    def create
      @listing = Listing.save_to_db(listing_params)
      if @listing
        render json: @listing
      else
        render json: @listing.errors.full_messages,
                     status: :unprocessable_entity
      end
    end

    def search
      @listings = filter(search_params)
      render :search
    end

    def show
      @listing = Listing.find(params[:id])
      render :show
    end

    private

    def filter(params)
      return [] if (params[:lat].empty? || params[:lng].empty?)

      price_min = params[:min]
      price_max = params[:max]
      lat_min, lat_max = params[:lat]
      lng_min, lng_max = params[:lng]
      listings = Listing.where(latitude: lat_min..lat_max)
                        .where(longitude: lng_min..lng_max)
      if price_min != "-1"
        listings = listings.where(price_daily: price_min..price_max)
      end

      listings
    end

    def search_params
      params.require(:search).permit(:min, :max, :lat => [], :lng => [])
    end

    def listing_params
      params.require(:listing).permit(:title, :address, :description, :city,
                                      :state, :price)
    end
  end
end

app/controllers/api/reservations_controller.rb
module Api
  class ReservationsController < ApplicationController
    def create
      @reservation = current_user.reservations.new(reservation_params)
      if @reservation.try_booking
        render :show
      else
        render json: @reservation.errors.full_messages,
                     status: :unprocessable_entity
      end
    end

    def show
      @reservation = Reservation.find(params[:id])
      render :show
    end

    private

    def reservation_params
      params.require(:reservation).permit(:listing_id,
                                          :start_date,
                                          :end_date)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :auth_input, :logged_in?

  def auth_input
    "<input type='hidden' name='authenticity_token'
      value=#{form_authenticity_token}>".html_safe
  end

  def current_user
    return nil if current_session.nil?
    @current_user ||= User.find(current_session.user_id)
  end

  def current_session
    return nil if session[:session_token].nil?
    @current_session ||= Session.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    @current_session = Session.create!(user_id: user.id,
                                       session_token: Session.generate_session_token)
    session[:session_token] = @current_session.session_token
  end

  def logout!
    current_session.try(:remove_session!)
    session[:session_token] = nil
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def redirect_if_logged_in
    redirect_to user_url(current_user) if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, only: [:create]
  before_filter :logged_in?, only: [:destroy]

  def create
    @user = User.find_by_credentials(user_params)
    if @user
      login!(@user)
      render json: @user
    else
      render json: 'Incorrect credentials'.to_json,
                   status: :unprocessable_entity
    end
  end

  def destroy
    logout!
    redirect_to :root
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_logged_in, only: [:create]

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      render json: @user
    else
      render json: @user.errors.full_messages,
                   status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
    if @user
      render :show
    else
      redirect_to :root
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- insert api key with code snippet, and whitelist heroku app on google API -->
  <title>PetBnB</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'https://s3-us-west-1.amazonaws.com/petbnb/images/favicon.ico' %>

  <% if Rails.env.production? %>
    <% api_key = 'key=AIzaSyBFim-M4UMUmjfmk1y5ss_Kd7B_3ooi9iM&' %>
  <% else %>
    <% api_key = '' %>
  <% end %>

  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?<%= api_key %>libraries=places">
    </script>
</head>
<body>

  <%= render 'shared/navbar' %>

  <div id="content">
    <%= yield %>
  </div>

  <div id="modals">
    <%= render 'shared/modals' %>
  </div>

  <script charset="utf-8">
  </script>

</body>
</html>

app/views/shared/_modal_form.html.erb
<div class="modal-dialog modal-sm">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal"
              aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title" id="myModalLabel"><%= title %></h4>
    </div>
    <form action="<%= action %>" method="post">
      <%= auth_input %>
      <div class="modal-body">
        <div class="errors">
        </div>
        <div class="modal-body row">
          Email: <input id='email'
                        type="text"
                        class="form-control"
                        name="user[email]"
                        value="">
          Password: <input type="password"
                           class="form-control"
                           name="user[password]">
        </div>
        <div class="modal-body-row">
          <button type="submit" class="btn btn-primary"
                  id="<%= title.split.join('').downcase %>">
            <%= title %>
          </button>
          <% if title == 'Log in' %>
            <button type="submit" class="btn btn-primary btn-info"
                    id="guest-login">
              Guest login
            </button>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <% if title == 'Log in' %>
          Don't have an account?
          <a href="#" id='signupLink'
             data-toggle="modal" data-target="#signupModal">Sign up</a>
        <% else %>
          Already a PetBnB member?
          <a href="#" id='loginLink'
             data-toggle="modal" data-target="#loginModal">Log in</a>
        <% end %>
      </div>
    </form>
  </div>
</div>

app/views/shared/_modals.html.erb
<div class="modal fade" id="loginModal" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
  <%= render 'shared/modal_form', title: 'Log in', action: '/session' %>
</div>

<div class="modal fade" id="signupModal" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
  <%= render 'shared/modal_form', title: 'Sign up', action: '/users' %>
</div>

<script charset="utf-8">
  // focus on email field when modal pops up
  $('.modal').on('shown.bs.modal', function () {
    $('.modal.fade.in #email').focus();
  })

  // correctly hide current modal's elements when showing other one
  $('#loginLink').click(function () {
    $('#signupModal').hide();
    $('body').removeClass('.modal-open');
    $('.modal.in .errors').html('');
    $('.modal-backdrop').remove();
  });
  $('#signupLink').click(function () {
    $('#loginModal').hide();
    $('body').removeClass('.modal-open');
    $('.modal.in .errors').html('');
    $('.modal-backdrop').remove();
  });

  // click handlers for guest login, login, and signup buttons
  $('#guest-login').click(function (event) {
    event.preventDefault();
    $('.modal.in .errors').html('');
    $('.modal.in button').prop('disabled', 'true');

    $('.modal.in').find('#email').val('');
    $('.modal.in').find('input[type=password]').val('');
    animateGuestLogin();
  });
  $('#login').click(function (event) {
    event.preventDefault();
    $('.modal.in .errors').html('');
    $('.modal.in button').prop('disabled', 'true');

    loginOrSignup({
      action: '/session',
      email: $('.modal.in').find('#email').val(),
      password: $('.modal.in').find('input[type=password]').val()
    });
  });
  $('#signup').click(function (event) {
    event.preventDefault();
    $('.modal.in .errors').html('');
    $('.modal.in button').prop('disabled', 'true');

    loginOrSignup({
      action: '/users',
      email: $('.modal.in').find('#email').val(),
      password: $('.modal.in').find('input[type=password]').val()
    });
  });

  // create new user or session
  function loginOrSignup(options) {
    var userData = { user: { email: options.email,
                             password: options.password }};
    $.ajax({
      url: options.action,
      type: 'POST',
      data: userData,
      success: function () {
        window.location.replace('');
      },
      error: function (response) {
        var errors = '';
        if (options.action === '/users') {
          if (response.responseJSON) {
            response.responseJSON.forEach(function (error) {
              errors += (error + '<br>');
            });
          }
        } else {
          errors += 'Incorrect credentials<br>';
        }
        $('.modal.in .errors').html(errors);
        $('.modal.in button').removeAttr('disabled');
      }
    });
  };

  // animate guest login key entries
  function animateGuestLogin() {
    var text = 'Guestpassword';
    var index = 0;
    var enterText = setInterval(function () {
      var field = $('.modal.in').find('#email');
      if (index > 4) {
        field = $('.modal.in').find('input[type=password]');
      }
      var currentVal = field.val();
      field.val(currentVal + text[index]);

      index++;
      if (index >= text.length) {
        clearInterval(enterText);
        loginOrSignup({
          action: '/session',
          email: 'Guest',
          password: 'password'
        });
      }
    }, 50);
  };

</script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/">
        <%= image_tag('https://s3-us-west-1.amazonaws.com/petbnb/images/logo_icon.png',
                      size: '50x50',
                      class: 'navbar-brand pull-right',
                      alt: 'logo') %>
      </a>
      <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse"
              data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div id="navbar-search-container" class="">
        <form class="navbar-form navbar-left" role="search">
          <input type="text" class="form-control" id="navbar-searchbox"
                 placeholder="Where is your pet going?">
        </form>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <input type="hidden" id="logged_in" value="<%= current_user.id %>">
          <!-- <li>
            <div id="new-listing-button">
              <a class="btn btn-primary" href="#listings/new">List Your Space</a>
            </div>
          </li> -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-expanded="false">
              <%= current_user.email %><span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <a href="#/profile">
                  View Profile
                </a>
              </li>
            </ul>
          </li>
          <li>
            <%= link_to 'Log out', session_url, method: :delete %>
          </li>
        <% else %>
          <li>
            <a href="#" data-toggle="modal"
               data-target="#loginModal">Log In</a>
          </li>
          <li>
            <a href="#" data-toggle="modal"
               data-target="#signupModal">Sign Up</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<script type="text/javascript">
  (function () {
    $('#navbar-search-container input').keydown(function(event) {
      if (event.keyCode === 13) {
        event.preventDefault();
      }
    });
  })();
</script>

app/views/static_pages/index.html.erb
<div class="intro-wrapper">
  <div class="intro-text">
    VACATION HOMES FOR YOUR PET
    <% if !logged_in? %>
      <div class="welcome-text">
        Welcome to PetBnB :)
        <br>
        Please login or sign up with the links on the top right!
      </div>
    <% end %>
  </div>
  <% if logged_in? %>
    <div class="intro-search">
      <form class="form-group form-inline search-bar">
        <%= auth_input %>
        <div class="input-group">
          <span class="input-group">
            <input type="text" class="form-control search"
                   name="search[location]"
                   id="homepage-searchbox"
                   placeholder="Where does your pet want to go?">
            <span class="errors"></span>
          </span>
          <span class="input-group hidden-xs">
            <input type="text" class="form-control"
                   id="checkin"
                   name="search[checkin]"
                   placeholder="Check In">
          </span>
          <span class="input-group hidden-xs">
            <input type="text" class="form-control"
                   id="checkout"
                   name="search[checkout]"
                   placeholder="Check Out">
          </span>
          <span class="input-group-btn">
            <button class="btn btn-primary search">Search</button>
          </span>
        </div>
      </form>
    </div>
  <% end %>
</div>
<% if logged_in? %>
  <div class="intro-listings">
    <div class="panel panel-dark">
      <div class="discovery-container">
        <div class="discovery-text text-center row-space-6 row-space-top-8">
          <h2>Friendly hosts</h2>
          <p>Pamper your pet while you travel</p>
        </div>
        <div class="discovery-tiles row">
          <div class="col-md-6 col-sm-12">
            <div class="discovery-tile" style="background: url('https://s3-us-west-1.amazonaws.com/petbnb/images/listings/listing1b.jpg');">
              <a href="#/listings/1">
                <div class="va-middle text-center">Noe Valley</div>
              </a>
            </div>
          </div>
          <div class="col-md-6 col-sm-12">
            <div class="discovery-tile" style="background: url('https://s3-us-west-1.amazonaws.com/petbnb/images/listings/listing4a.jpg');">
              <a href="#/listings/4">
                <div class="va-middle text-center">SOMA</div>
              </a>
            </div>
          </div>
        </div>
        <div class="discovery-footer">
          <button type="button" class="btn btn-large btn-block listings">
            See More Listings in California
          </button>
        </div>
      </div>
    </div>
  </div>

  <script charset="utf-8">
    $(document).ready(function () {
      $('#checkin').datepicker({ minDate: 1 });
      $('#checkout').datepicker({ minDate: 1 });
    })
  </script>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','http://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-63567649-1', 'auto');
    ga('send', 'pageview');
  </script>
<% end %>